title: Jeff the Coder
email: jeffguorg@gmail.com
description: >
  Hi, this is Jeff the software engineer working in Shanghai. 
  Here is some notes during my work and life. 
  Well...no work, just fun.
baseurl: ""
url: "https://jeffguorg.github.io"
twitter_username: jeffguorg
github_username:  jeffguorg

markdown: kramdown

theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap